### ISSUE TITLE
Add download from GitHub feature

### ISSUE THREAD

**Issue by STiXzoOR** [the-braveknight/macos-tools#1]
hey, can you implement a way to download kexts from github? thanks

**Comment by the-braveknight** [comment]
Not a good idea. Kexts need to be compiled after the source code is downloaded and it’s not always possible to do that in a script (source needs to include a makefile). Also the kext(s) might require some dependencies that are not preset.

**Comment by STiXzoOR** [comment]
i'm not saying download the whole source code, just the latest release file. I'm interested in some lilu plugins.

**Comment by the-braveknight** [comment]
Well not all lilu plugins provide release files. Can you provide some examples of the plugins you’d like to download?

**Comment by STiXzoOR** [comment]
Mainly AppleALC and IntelGraphicsDVMTFixup and maybe Shiki

**Comment by the-braveknight** [comment]
I’ll try to see if I can write a script to fetch common Lilu plugins soon when I have time.

**Comment by STiXzoOR** [comment]
ok thanks man

**Comment by the-braveknight** [comment]
You should check my latest github_download.sh script.

**Comment by STiXzoOR** [comment]
cool thanks a lot dude
