### ISSUE TITLE
Kexts on EFI don't get deleted

### ISSUE THREAD

**Issue by STiXzoOR** [the-braveknight/macos-tools#2]
there is an issue where the kexts on EFI don't get deleted after installing the new ones. I think the problem is with this line: `rm -Rf $kext_dest/*.kext` in the _hack_cmds.sh. It should be `rm -Rf $efi_kext_dest/*.kext`.

EDIT: also can we make the `org.the-braveknight.essential.plist` and `org.the-braveknight.deprecated.plist` as local plists so everyone can modify them to their own needs? Thanks.

**Comment by the-braveknight** [comment]
I will try to figure out a way to override essentials and deprecated kexts, I don't want to change the current behavior because those kexts are the same for almost all hacks now.

**Comment by STiXzoOR** [comment]
Cool thanks man
