### ISSUE TITLE
[Feature Request] Add option to not install custom AppleHDA kext

### ISSUE THREAD

**Issue by STiXzoOR** [the-braveknight/macos-tools#3]
Hello, will it be possible to add a check function or something so if there is no `Codec` entry in the plist, it will not create the custom AppleHDA kext? This is useful for people who uses AppleALC. Thanks.

**Comment by the-braveknight** [comment]
Will look into that later today.

**Comment by the-braveknight** [comment]
It is possible to add this feature, but I would rather just remove the AppleHDA injector creation commands from _hack_cmds.sh. I am just waiting for the next AppleALC release that has my custom layout resources.

**Comment by STiXzoOR** [comment]
hmm but will i be able to still use the AppleHDA injector method in the future by putting the commands in the installation script file? i'm asking this because on my laptop the AppleALC doesn't seem to work in the past although i found today that the files were wrong so i pulled a request to merge the AppleHDA files with the AppleALC's hopefully this time it will work.

**Comment by the-braveknight** [comment]
I think AppleALC is the future. I filed a PR to add support for my custom layout files to AppleALC and it was merged. I think the devs are very friendly and you can add support to your codec very easily. For now, I am just waiting for the next AppleALC release to remove AppleHDA injector commands from _hack_cmds.sh script. However, AppleHDA patching scripts will still be available for those who prefer it.

**Comment by STiXzoOR** [comment]
Well i did filed a pull request but it got revoked because apparently i broke PinConfigs XML stracture or something
